version: '3'

services:
  mongo:
    container_name: mongodb
    image: mongo    
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123
        MONGO_INITDB_DATABASE: admin
    volumes:
      - C:/Users/marco/mongodb/data:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge